FROM dxflrs/garage:v2.0.0 AS build
FROM alpine AS runner
RUN apk update && apk add envsubst
COPY --from=build / /
WORKDIR /app
COPY ./build.sh .
COPY ./garage.tmpl.toml .
RUN chmod +x ./build.sh
ENV RUST_BACKTRACE=1
ENV RUST_LOG=garage=info
CMD ["./build.sh"]