services:
  garage:
    build:
      context: .
      dockerfile: Dockerfile.garage
    container_name: garaged
    restart: unless-stopped          
    ports:
      - "3900:3900"                  
      - "3901:3901"                  
      - "3902:3902"                  
      - "3903:3903"                  
    volumes:
      - garage-meta:/var/lib/garage/meta 
      - garage-data:/var/lib/garage/data 
    environment:
      - 'RPC_SECRET=${RPC_SECRET}'
      - 'ADMIN_TOKEN=${ADMIN_TOKEN}'
      - 'METRICS_TOKEN=${METRICS_TOKEN}'

  webui:
    build:
      context: .
      dockerfile: Dockerfile.garage-web
    container_name: garage-webui
    restart: unless-stopped
    ports:
      - 3909:3909
    environment:
      - 'API_BASE_URL=http://garage:3903'
      - 'S3_ENDPOINT_URL=http://garage:3900'
      - 'RPC_SECRET=${RPC_SECRET}'
      - 'ADMIN_TOKEN=${ADMIN_TOKEN}'
      - 'METRICS_TOKEN=${METRICS_TOKEN}'    

volumes:
  garage-meta:
  garage-data: