services:
  garage:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: garaged
    restart: unless-stopped
    volumes:
      - garage-meta:/var/lib/garage/meta 
      - garage-data:/var/lib/garage/data 
    environment:
      - 'RPC_SECRET=${RPC_SECRET}'
      - 'ADMIN_TOKEN=${ADMIN_TOKEN}'
      - 'METRICS_TOKEN=${METRICS_TOKEN}'      

  webui:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: garage-webui
    restart: unless-stopped
    environment:
      - 'API_BASE_URL=http://garage:3903'
      - 'S3_ENDPOINT_URL=http://garage:3900'
      - 'RPC_SECRET=${RPC_SECRET}'
      - 'ADMIN_TOKEN=${ADMIN_TOKEN}'
      - 'METRICS_TOKEN=${METRICS_TOKEN}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3909"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - garage

volumes:
  garage-meta:
  garage-data: